### ISSUE TITLE
Examples fail to run correctly

### ISSUE THREAD

**Issue by srvasn** [flavienbwk/flbw#2]
The below command should return string as output, but it fails with the prompt "Wrong password"

`./flbw dec bp 1000 password $(./flbw enc bp 1000 password string)`

It works fine upon removing `bp 1000`.

**Comment by flavienbwk** [comment]
Hi @srvasn , 

Sorry for the late reply and thank you for your interest in FLBW.

Correct CLI usage is : 

```
./flbw decbp 1000 password
```

_Note there's no space between `dec` and `bp`_
